#ifndef NODE_H
#define NODE_H
#include "Matrix.h"

class Node {
	public:
	Node(unsigned int index,unsigned int id, std::string name);
	float getProbability(unsigned int nv, unsigned int pv);
	float getProbability(std::string nv, std::string pv);
	float getProbability(unsigned int nv, unsigned int pv) const;
	float getProbability(const std::string& nv, const std::string& pv) const;	
	void setProbability(float value, unsigned int nv, unsigned int pv);
	void setProbability(float value, const std::string& nv, const std::string& pv);
	unsigned int getObservations(unsigned int nv, unsigned int pv) ;
	unsigned int getObservations(const std::string& nv, const std::string& pv) ;
	unsigned int getObservations(unsigned int nv, unsigned int pv) const ;
	unsigned int getObservations(const std::string& nv, const std::string& pv) const ;	
	void setObservations(int value, unsigned int nv, unsigned int pv);
	void setObservations(int value, std::string nv, std::string pv);
	void setProbability(Matrix<float> m);	
	void setProbabilityTo1(std::string value);
	void setProbabilityTo1(int value);
	void createBackupDoIntervention();
	void loadBackupDoIntervention();
	void setObservations(Matrix<int> m);
	void setObservationBackup(Matrix<int> m);
	std::string& getName();
	const std::string& getName() const;
	unsigned int& getIndex();
	const unsigned int& getIndex() const;
	unsigned int& getID();
	const unsigned int& getID() const;
	bool hasValue(std::string v) const;
	std::vector<unsigned int>& getParents();
	const std::vector<unsigned int>& getParents() const;
	void setParents(std::vector<unsigned int> parents);
	void cutParents();
	void setUniqueValues(std::vector<int> uniqueValues);
	std::vector<int>& getUniqueValues();
	const std::vector<int>& getUniqueValues() const;
	void setUniqueValuesExcludingNA(std::vector<int>);
	std::vector<int>& getUniqueValuesExcludingNA();
	const std::vector<int>& getUniqueValuesExcludingNA() const;
	void setObservationRow(int row);
	int getObservationRow();
	const int getObservationRow() const;
	void setParentCombinations(int row);
	int getParentCombinations();
	const int getParentCombinations() const;
	void setValueNames(std::vector<std::string> valueNames);
	void addValueName(std::string name);
	std::vector<std::string>& getValueNames();
	const std::vector<std::string>& getValueNames() const;
	void setValueNamesProb(std::vector<std::string> valueNames);
	void addValueNameProb(std::string name);
	std::vector<std::string>& getValueNamesProb();
	const std::vector<std::string>& getValueNamesProb() const;
	void setParentValueNames(std::vector<std::string> valueNames); 
	void addParentValueName(std::string name);
	std::vector<std::string>& getParentValueNames();		
	const std::vector<std::string>& getParentValueNames() const;
	Matrix<float>& getProbabilityMatrix();
	const Matrix<float>& getProbabilityMatrix() const;
	int getIndex(const std::string& value);
	const int getIndex(const std::string& value) const;
	Matrix<int>& getObservationMatrix();
	const Matrix<int>& getObservationMatrix() const;
	void createBackup();
	void loadBackup();
	void setUnvisited();
	void visit();
	bool isVisited() const;
	void clearNameVectors();
	friend std::ostream& operator<< (std::ostream& os,const Node& n);
	private:
	unsigned int index_;
	unsigned int id_;
	std::vector<unsigned int> Parents_;
	std::vector<unsigned int> ParentsBackup_;
	std::string name_;
	Matrix<float> ProbabilityMatrix_;
	Matrix<float> ProbabilityMatrixBackup_;
	Matrix<int> ObservationMatrix_;
	Matrix<int> ObservationBackup_;
	std::vector<int> uniqueValues_;
	std::vector<std::string> valueNames_;
	std::vector<std::string> valueNamesProb_;
	std::vector<std::string> parentValueNames_;
	std::vector<int> uniqueValuesExcludingNA_;
	int observationRow_;
	int parentCombinations_;
	bool visited_=false;
};
#endif
